import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const { client, address, budget, notes, needsRender } = await req.json();

    const systemPrompt = `You are Greenscape Pro - an expert landscape designer for Marcus Tate in Phoenix, AZ. 
Create a client-ready proposal. Be concise, professional, itemized. 
Include: Scope, Materials (pavers, low-water plants), Timeline 2-3 weeks, Terms 50% deposit via Stripe, 3D render note if needed.
Budget: ${budget}. Format in markdown with pricing.`;

    const userPrompt = `Client: ${client}
Address: ${address}
Budget: ${budget}
Site Notes: ${notes}
Needs 3D Render: ${needsRender ? 'Yes - include $500 render fee' : 'No'}

Generate proposal now. End with Total and Next Steps.`;

    let proposalText = "";

    // Try Claude if key exists
    if (process.env.ANTHROPIC_API_KEY) {
      const anthRes = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": process.env.ANTHROPIC_API_KEY,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({
          model: "claude-3-5-sonnet-20241022",
          max_tokens: 1500,
          system: systemPrompt,
          messages: [{ role: "user", content: userPrompt }]
        })
      });
      const data = await anthRes.json();
      proposalText = data?.content?.[0]?.text || JSON.stringify(data);
    } else {
      // MOCK for now (works without API key)
      proposalText = `# Greenscape Pro Proposal
**Client:** ${client}
**Address:** ${address}
**Budget:** ${budget}

### Scope of Work
- Demo & prep backyard 40x30
- Install paver patio 20x20 - Travertine, permeable base
- Low-water planting: Agave, Desert Spoon, Lantana (15 plants)
- Firepit - gas, 48" steel with lava rock
- LED low-voltage lighting (6 fixtures)

### Investment
- Hardscape: $18,500
- Plants & Irrigation: $4,200
- Firepit: $3,800
- Lighting: $1,200
- ${needsRender ? '3D Render: $500' : 'Design: Included'}
**Total: ${budget}**

### Timeline
Site Walk Done → AI Drafted → Awaiting Approval → Sent
2 weeks build. 50% deposit via Stripe.

### Notes
${notes}

*Generated by Claude 3.5 Sonnet • Human approval required*
`;
    }

    // Try save to Supabase if keys exist
    if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY) {
      try {
        const { createClient } = await import('@supabase/supabase-js');
        const supabase = createClient(
          process.env.NEXT_PUBLIC_SUPABASE_URL!,
          process.env.SUPABASE_SERVICE_ROLE_KEY!
        );
        await supabase.from('proposals').insert({
          client_name: client,
          address,
          budget,
          notes,
          proposal_text: proposalText,
          status: 'AI Drafted'
        });
      } catch (e) {
        console.log('Supabase save skipped:', e);
      }
    }

    return NextResponse.json({ text: proposalText });
  } catch (e: any) {
    return NextResponse.json({ text: `Error: ${e.message}` }, { status: 500 });
  }
}
